/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReadRouteImport } from './routes/read'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CollabRouteImport } from './routes/collab'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as NovelNovelIdRouteImport } from './routes/novel.$novelId'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedWorkspaceNovelIdRouteImport } from './routes/_authenticated/workspace.$novelId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabRoute = CollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelNovelIdRoute = NovelNovelIdRouteImport.update({
  id: '/novel/$novelId',
  path: '/novel/$novelId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceNovelIdRoute =
  AuthenticatedWorkspaceNovelIdRouteImport.update({
    id: '/workspace/$novelId',
    path: '/workspace/$novelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collab': typeof CollabRoute
  '/community': typeof CommunityRoute
  '/contests': typeof ContestsRoute
  '/faq': typeof FaqRoute
  '/rankings': typeof RankingsRoute
  '/read': typeof ReadRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/novel/$novelId': typeof NovelNovelIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/workspace/$novelId': typeof AuthenticatedWorkspaceNovelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collab': typeof CollabRoute
  '/community': typeof CommunityRoute
  '/contests': typeof ContestsRoute
  '/faq': typeof FaqRoute
  '/rankings': typeof RankingsRoute
  '/read': typeof ReadRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/novel/$novelId': typeof NovelNovelIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/workspace/$novelId': typeof AuthenticatedWorkspaceNovelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/collab': typeof CollabRoute
  '/community': typeof CommunityRoute
  '/contests': typeof ContestsRoute
  '/faq': typeof FaqRoute
  '/rankings': typeof RankingsRoute
  '/read': typeof ReadRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/novel/$novelId': typeof NovelNovelIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/_authenticated/workspace/$novelId': typeof AuthenticatedWorkspaceNovelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/collab'
    | '/community'
    | '/contests'
    | '/faq'
    | '/rankings'
    | '/read'
    | '/search'
    | '/admin'
    | '/dashboard'
    | '/inbox'
    | '/library'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/upload'
    | '/novel/$novelId'
    | '/profile/$userId'
    | '/workspace/$novelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/collab'
    | '/community'
    | '/contests'
    | '/faq'
    | '/rankings'
    | '/read'
    | '/search'
    | '/admin'
    | '/dashboard'
    | '/inbox'
    | '/library'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/upload'
    | '/novel/$novelId'
    | '/profile/$userId'
    | '/workspace/$novelId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/collab'
    | '/community'
    | '/contests'
    | '/faq'
    | '/rankings'
    | '/read'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/library'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/upload'
    | '/novel/$novelId'
    | '/profile/$userId'
    | '/_authenticated/workspace/$novelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CollabRoute: typeof CollabRoute
  CommunityRoute: typeof CommunityRoute
  ContestsRoute: typeof ContestsRoute
  FaqRoute: typeof FaqRoute
  RankingsRoute: typeof RankingsRoute
  ReadRoute: typeof ReadRoute
  SearchRoute: typeof SearchRoute
  NovelNovelIdRoute: typeof NovelNovelIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab': {
      id: '/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof CollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novel/$novelId': {
      id: '/novel/$novelId'
      path: '/novel/$novelId'
      fullPath: '/novel/$novelId'
      preLoaderRoute: typeof NovelNovelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/$novelId': {
      id: '/_authenticated/workspace/$novelId'
      path: '/workspace/$novelId'
      fullPath: '/workspace/$novelId'
      preLoaderRoute: typeof AuthenticatedWorkspaceNovelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedWorkspaceNovelIdRoute: typeof AuthenticatedWorkspaceNovelIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedWorkspaceNovelIdRoute: AuthenticatedWorkspaceNovelIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CollabRoute: CollabRoute,
  CommunityRoute: CommunityRoute,
  ContestsRoute: ContestsRoute,
  FaqRoute: FaqRoute,
  RankingsRoute: RankingsRoute,
  ReadRoute: ReadRoute,
  SearchRoute: SearchRoute,
  NovelNovelIdRoute: NovelNovelIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
